services:
  postgres:
    container_name: recsis-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-recsis}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-recsis}
      PGDATA: /data/postgres
    volumes:
      #  - postgres:/data/postgres
       - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    container_name: recsis-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres
  
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
