// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package compare

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func scripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\r\n\t\tinitializeTooltips();\r\n\r\n\t\t// bootstrap tooltip removal\r\n\t\tfunction reloadTooltips() {\r\n\t\t\tconst tooltipTriggerList = document.querySelectorAll('[data-bs-toggle=\"tooltip\"]')\r\n\t\t\tconst tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => bootstrap.Tooltip.getInstance(tooltipTriggerEl).dispose())\r\n\r\n\t\t\tinitializeTooltips();\r\n\t\t};\r\n\r\n\t\t// bootstrap tooltip initialization\r\n\t\tfunction initializeTooltips() {\r\n\t\t\tconst tooltipTriggerList = document.querySelectorAll('[data-bs-toggle=\"tooltip\"]')\r\n\t\t\tconst tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))\r\n\t\t};\r\n\r\n\t\tfunction locateCourse(layout, side, code) {\r\n\t\t\tconst other = side === 'left' ? 'right' : 'left'\r\n\t\t\tconst query = `[data-plan-layout='${layout}'][data-plan-side='${other}'] [data-course-code='${code}']`\r\n\t\t\tconst targets = document.querySelectorAll(query)\r\n\t\t\tif (targets.length > 0) {\r\n\t\t\t\ttargets[0].scrollIntoView({ behavior: 'smooth', block: 'center' })\r\n\t\t\t\ttargets.forEach((el) => {\r\n\t\t\t\t\tel.classList.add('dp-compare-highlight')\r\n\t\t\t\t\tsetTimeout(() => el.classList.remove('dp-compare-highlight'), 3000);\r\n\t\t\t\t})\r\n\t\t\t}\t\r\n\t\t}\r\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
