CREATE DATABASE recsis;

CREATE USER elt WITH PASSWORD 'elt';
CREATE USER webapp WITH PASSWORD 'webapp';

-- -- GRANT ALL PRIVILEGES ON DATABASE recsis TO recsis;

\c recsis
CREATE SCHEMA elt AUTHORIZATION elt;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA elt GRANT ALL PRIVILEGES ON TABLES TO elt;

CREATE SCHEMA webapp AUTHORIZATION webapp;
-- GRANT USAGE ON SCHEMA webapp TO elt;
-- GRANT
--     DELETE,
--     INSERT
-- ON
--     webapp.courses,
--     webapp.degree_plans
-- TO elt;
-- -- ALTER DEFAULT PRIVILEGES IN SCHEMA webapp GRANT ALL PRIVILEGES ON TABLES TO webapp;
-- -- ALTER DEFAULT PRIVILEGES IN SCHEMA webapp GRANT ALL PRIVILEGES ON TABLES TO elt;

