INSERT INTO webapp.users(id) VALUES
('test-dsw'),
('test-dai'),
('test-dgd');

INSERT INTO webapp.studies(user_id, degree_plan_code, start_year) VALUES
('test-dsw', 'NIPVS19B', 2020),
('test-dai', 'NIUI25B', 2025),
('test-dgd', 'NIPGVAVH22B', 2022);

INSERT INTO webapp.blueprint_years(user_id, academic_year) VALUES
('test-dsw', 0),
('test-dai', 0),
('test-dgd', 0);

INSERT INTO webapp.blueprint_semesters(blueprint_year_id, semester) VALUES
((SELECT id FROM webapp.blueprint_years WHERE user_id='test-dsw' AND academic_year=0), 0),
((SELECT id FROM webapp.blueprint_years WHERE user_id='test-dai' AND academic_year=0), 0),
((SELECT id FROM webapp.blueprint_years WHERE user_id='test-dgd' AND academic_year=0), 0);

INSERT INTO webapp.blueprint_courses(blueprint_semester_id, course_code, course_valid_from, position) VALUES
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG062', 2022, 1),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG030', 2022, 2),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI120', 2022, 3),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI141', 2022, 4),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NDMI002', 2022, 5),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NMAI057', 2022, 6),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTVY014', 2022, 7),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTIN060', 2022, 8),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG031', 2022, 9),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI170', 2022, 10),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI177', 2022, 11),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NMAI054', 2022, 12),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NMAI058', 2022, 13),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTVY015', 2022, 14),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NDBI025', 2022, 15),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTIN061', 2022, 16),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NDMI011', 2022, 17),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NAIL062', 2022, 18),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI142', 2022, 19),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTVY016', 2022, 20),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG035', 2022, 22),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NJAZ091', 2022, 23),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTIN071', 2022, 24),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NMAI059', 2022, 25),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG045', 2022, 26),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI154', 2022, 27),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI041', 2022, 28),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NTVY017', 2022, 30),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI004', 2022, 31),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG041', 2022, 32),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG013', 2022, 33),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NSWI098', 2022, 35),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG043', 2022, 38),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG054', 2022, 39),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dsw' AND b.academic_year=0 AND bs.semester=0), 'NPRG042', 2022, 40);

-- All courses for test-dai (NIUI25B), using course_valid_from = 2025
INSERT INTO webapp.blueprint_courses(blueprint_semester_id, course_code, course_valid_from, position) VALUES
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG062', 2025, 1),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG030', 2025, 2),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NSWI120', 2025, 3),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NSWI141', 2025, 4),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NDMI002', 2025, 5),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NMAI057', 2025, 6),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTVY014', 2025, 7),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTIN060', 2025, 8),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG031', 2025, 9),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NSWI170', 2025, 10),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NSWI177', 2025, 11),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NMAI054', 2025, 12),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NMAI058', 2025, 13),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTVY015', 2025, 14),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTIN061', 2025, 15),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NDMI011', 2025, 16),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NAIL062', 2025, 17),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NMAI055', 2025, 18),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTVY016', 2025, 19),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NAIL028', 2025, 20),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG041', 2025, 21),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NJAZ091', 2025, 22),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTIN071', 2025, 23),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NMAI059', 2025, 24),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG045', 2025, 25),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NAIL120', 2025, 26),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG005', 2025, 27),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NTVY017', 2025, 28),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG051', 2025, 29),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NDBI025', 2025, 30),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPFL129', 2025, 31),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPFL012', 2025, 32),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPRG013', 2025, 33),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPGR036', 2025, 34),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NAIL121', 2025, 35),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dai' AND b.academic_year=0 AND bs.semester=0), 'NPFL124', 2025, 36);

-- All courses for test-dgd (NIPGVAVH22B), using course_valid_from = 2022
INSERT INTO webapp.blueprint_courses(blueprint_semester_id, course_code, course_valid_from, position) VALUES
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG062', 2022, 1),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG030', 2022, 2),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NSWI120', 2022, 3),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NSWI141', 2022, 4),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NDMI002', 2022, 5),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NMAI057', 2022, 6),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTVY014', 2022, 7),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTIN060', 2022, 8),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG031', 2022, 9),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NSWI170', 2022, 10),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NSWI177', 2022, 11),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NMAI054', 2022, 12),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NMAI058', 2022, 13),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTVY015', 2022, 14),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTIN061', 2022, 15),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NDMI011', 2022, 16),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPGR003', 2022, 17),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NMAI055', 2022, 18),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG041', 2022, 19),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG035', 2022, 20),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTVY016', 2022, 21),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPGR037', 2022, 22),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NJAZ091', 2022, 23),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTIN071', 2022, 24),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NMAI059', 2022, 25),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPRG045', 2022, 26),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NTVY017', 2022, 27),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NDBI025', 2022, 28),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NAIL062', 2022, 29),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPGR025', 2022, 31),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPGR002', 2022, 32),
((SELECT bs.id FROM webapp.blueprint_years b LEFT JOIN webapp.blueprint_semesters bs ON b.id = bs.blueprint_year_id WHERE b.user_id='test-dgd' AND b.academic_year=0 AND bs.semester=0), 'NPGR035', 2022, 33);
