environment = "development"

[server]

[server.https]
port = 8000

[postgres]
host     = "localhost"
port     = 5432
user     = "webapp"
dbname   = "recsis"

[meilisearch]
host = "http://localhost:7700"

[recommender]
host = "localhost"
port = 8002

[cas]
host = "localhost:8001"

[ssl]
certificate = "cert/server.crt"
key 	    = "cert/server.key"
